"""Command-line interface for inspecting OrbitOps artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import typer
from pydantic import ValidationError

from orbitops.domain.models import Scenario

app = typer.Typer(
    name="orbitops",
    help="Reproducible satellite scheduling experiments.",
    no_args_is_help=True,
)


@app.command("validate")
def validate_scenario(
    scenario_path: Annotated[Path, typer.Argument(exists=True, dir_okay=False, readable=True)],
) -> None:
    """Validate a scenario against the v0.1 domain contract."""

    try:
        scenario = Scenario.from_json(scenario_path)
    except (OSError, ValidationError) as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=1) from exc

    typer.echo(
        json.dumps(
            {
                "valid": True,
                "schema_version": scenario.schema_version,
                "scenario_id": scenario.scenario_id,
                "task_count": len(scenario.tasks),
            },
            indent=2,
        )
    )


@app.command("schema")
def print_schema(
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", dir_okay=False, help="Write the schema to a file."),
    ] = None,
) -> None:
    """Print or write the authoritative JSON Schema generated by the domain model."""

    rendered = json.dumps(Scenario.model_json_schema(), indent=2, sort_keys=True) + "\n"
    if output is None:
        typer.echo(rendered, nl=False)
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    typer.echo(f"Wrote {output}")
