"""Command-line interface for inspecting OrbitOps artifacts."""

from __future__ import annotations

import json
from enum import StrEnum
from pathlib import Path
from typing import Annotated

import typer
from pydantic import ValidationError

from orbitops.domain.models import Scenario, Schedule
from orbitops.simulation.validator import validate_schedule

app = typer.Typer(
    name="orbitops",
    help="Reproducible satellite scheduling experiments.",
    no_args_is_help=True,
)


class SchemaTarget(StrEnum):
    SCENARIO = "scenario"
    SCHEDULE = "schedule"


@app.command("validate")
def validate_scenario(
    scenario_path: Annotated[Path, typer.Argument(exists=True, dir_okay=False, readable=True)],
) -> None:
    """Validate a scenario against the v0.1 domain contract."""

    try:
        scenario = Scenario.from_json(scenario_path)
    except (OSError, ValidationError) as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=1) from exc

    typer.echo(
        json.dumps(
            {
                "valid": True,
                "schema_version": scenario.schema_version,
                "scenario_id": scenario.scenario_id,
                "task_count": len(scenario.tasks),
            },
            indent=2,
        )
    )


@app.command("schema")
def print_schema(
    target: Annotated[
        SchemaTarget,
        typer.Option("--target", "-t", help="Select the contract to export."),
    ] = SchemaTarget.SCENARIO,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", dir_okay=False, help="Write the schema to a file."),
    ] = None,
) -> None:
    """Print or write the authoritative JSON Schema generated by the domain model."""

    model = Scenario if target is SchemaTarget.SCENARIO else Schedule
    rendered = json.dumps(model.model_json_schema(), indent=2, sort_keys=True) + "\n"
    if output is None:
        typer.echo(rendered, nl=False)
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    typer.echo(f"Wrote {output}")


@app.command("check")
def check_schedule(
    scenario_path: Annotated[Path, typer.Argument(exists=True, dir_okay=False, readable=True)],
    schedule_path: Annotated[Path, typer.Argument(exists=True, dir_okay=False, readable=True)],
) -> None:
    """Simulate a schedule and report every violated hard constraint."""

    try:
        scenario = Scenario.from_json(scenario_path)
        schedule = Schedule.from_json(schedule_path)
    except (OSError, ValidationError) as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=1) from exc

    report = validate_schedule(scenario, schedule)
    payload = report.model_dump(mode="json", exclude_none=True)
    payload["is_feasible"] = report.is_feasible
    typer.echo(json.dumps(payload, indent=2))
    if not report.is_feasible:
        raise typer.Exit(code=1)
